### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ibsali33**
Edits to Step1

### CODE REVIEW

**Review by sarahemlin — COMMENTED** [review]
Hi @ibsali33 --
I don't know about @gvwilson , but I feel fairly strongly about keeping the word users on line 81.  I'm ok with all the other changes (I particularly like lines 70-77).

Sarah

**Comment by ibsali33** [comment]
I hear you about using the term users. I noticed in later edits that I was interchanging between the terms reader and user - and I switched everything back to the term user since it makes more sense.

**Review by sarahemlin — CHANGES_REQUESTED** [review]
@ibsali33 --

I think you'll need to push changes again so that the change to readers is reverted.  Then I can merge this pull request.  Thank you!

Sarah

**Comment by ibsali33** [comment]
Sorry, I'm still learning how to do these pull requests properly. So in a later pull request that I submitted (titled 'Minor Edits in Steps 3, 4 5 and 9') I reverted the changes back from readers to users. Would you still like me to change it on this pull request? We'll run into the same issue on my 'Edits for Step 2' since I built on my edits from step 1 in that pull request.

**Comment by ibsali33** [comment]
I think I fixed it.

**Pull request merged**
